/**
 * Script de génération des communes IDF manquantes
 * Source: Données INSEE officielles
 * 
 * Usage: npx tsx scripts/generate-cities.ts
 */

// Données des communes IDF par département
// Source: INSEE Code Officiel Géographique 2024

interface CityData {
  slug: string;
  name: string;
  postalCodes: string[];
  department: string;
  departmentName: string;
  population?: number;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

// Seine-et-Marne (77) - Communes complémentaires
const seinEtMarneExtra: CityData[] = [
  { slug: "acheres-la-foret", name: "Achères-la-Forêt", postalCodes: ["77760"], department: "77", departmentName: "Seine-et-Marne", population: 1124 },
  { slug: "amillis", name: "Amillis", postalCodes: ["77120"], department: "77", departmentName: "Seine-et-Marne", population: 1018 },
  { slug: "andrezel", name: "Andrezel", postalCodes: ["77390"], department: "77", departmentName: "Seine-et-Marne", population: 715 },
  { slug: "annet-sur-marne", name: "Annet-sur-Marne", postalCodes: ["77410"], department: "77", departmentName: "Seine-et-Marne", population: 3256 },
  { slug: "arbonne-la-foret", name: "Arbonne-la-Forêt", postalCodes: ["77630"], department: "77", departmentName: "Seine-et-Marne", population: 1036 },
  { slug: "armentières-en-brie", name: "Armentières-en-Brie", postalCodes: ["77440"], department: "77", departmentName: "Seine-et-Marne", population: 1785 },
  { slug: "aubepierre-ozouer-le-repos", name: "Aubepierre-Ozouer-le-Repos", postalCodes: ["77720"], department: "77", departmentName: "Seine-et-Marne", population: 567 },
  { slug: "aufferville", name: "Aufferville", postalCodes: ["77570"], department: "77", departmentName: "Seine-et-Marne", population: 813 },
  { slug: "avon", name: "Avon", postalCodes: ["77210"], department: "77", departmentName: "Seine-et-Marne", population: 13741 },
  { slug: "bagneaux-sur-loing", name: "Bagneaux-sur-Loing", postalCodes: ["77167"], department: "77", departmentName: "Seine-et-Marne", population: 1614 },
  { slug: "balloy", name: "Balloy", postalCodes: ["77118"], department: "77", departmentName: "Seine-et-Marne", population: 389 },
  { slug: "bannost-villegagnon", name: "Bannost-Villegagnon", postalCodes: ["77970"], department: "77", departmentName: "Seine-et-Marne", population: 608 },
  { slug: "barbey", name: "Barbey", postalCodes: ["77130"], department: "77", departmentName: "Seine-et-Marne", population: 354 },
  { slug: "barbizon", name: "Barbizon", postalCodes: ["77630"], department: "77", departmentName: "Seine-et-Marne", population: 1245 },
  { slug: "barcy", name: "Barcy", postalCodes: ["77910"], department: "77", departmentName: "Seine-et-Marne", population: 476 },
  { slug: "bassevelle", name: "Bassevelle", postalCodes: ["77750"], department: "77", departmentName: "Seine-et-Marne", population: 259 },
  { slug: "bazoches-les-bray", name: "Bazoches-lès-Bray", postalCodes: ["77118"], department: "77", departmentName: "Seine-et-Marne", population: 523 },
  { slug: "beauchery-saint-martin", name: "Beauchery-Saint-Martin", postalCodes: ["77560"], department: "77", departmentName: "Seine-et-Marne", population: 697 },
  { slug: "beaumont-du-gatinais", name: "Beaumont-du-Gâtinais", postalCodes: ["77890"], department: "77", departmentName: "Seine-et-Marne", population: 1125 },
  { slug: "beautheil-saints", name: "Beautheil-Saints", postalCodes: ["77120"], department: "77", departmentName: "Seine-et-Marne", population: 1012 },
  { slug: "beauvoir", name: "Beauvoir", postalCodes: ["77390"], department: "77", departmentName: "Seine-et-Marne", population: 328 },
  { slug: "bellot", name: "Bellot", postalCodes: ["77510"], department: "77", departmentName: "Seine-et-Marne", population: 878 },
  { slug: "bernay-vilbert", name: "Bernay-Vilbert", postalCodes: ["77540"], department: "77", departmentName: "Seine-et-Marne", population: 1124 },
  { slug: "beton-bazoches", name: "Beton-Bazoches", postalCodes: ["77320"], department: "77", departmentName: "Seine-et-Marne", population: 541 },
  { slug: "blandy", name: "Blandy", postalCodes: ["77115"], department: "77", departmentName: "Seine-et-Marne", population: 840 },
  { slug: "blennes", name: "Blennes", postalCodes: ["77940"], department: "77", departmentName: "Seine-et-Marne", population: 317 },
  { slug: "bois-le-roi", name: "Bois-le-Roi", postalCodes: ["77590"], department: "77", departmentName: "Seine-et-Marne", population: 5867 },
  { slug: "boissettes", name: "Boissettes", postalCodes: ["77350"], department: "77", departmentName: "Seine-et-Marne", population: 456 },
  { slug: "boissise-la-bertrand", name: "Boissise-la-Bertrand", postalCodes: ["77350"], department: "77", departmentName: "Seine-et-Marne", population: 1203 },
  { slug: "boissise-le-roi", name: "Boissise-le-Roi", postalCodes: ["77310"], department: "77", departmentName: "Seine-et-Marne", population: 4563 },
  { slug: "boissy-aux-cailles", name: "Boissy-aux-Cailles", postalCodes: ["77760"], department: "77", departmentName: "Seine-et-Marne", population: 367 },
  { slug: "boissy-le-chatel", name: "Boissy-le-Châtel", postalCodes: ["77169"], department: "77", departmentName: "Seine-et-Marne", population: 3012 },
  { slug: "boitron", name: "Boitron", postalCodes: ["77750"], department: "77", departmentName: "Seine-et-Marne", population: 264 },
  { slug: "bombon", name: "Bombon", postalCodes: ["77720"], department: "77", departmentName: "Seine-et-Marne", population: 1245 },
  { slug: "bougligny", name: "Bougligny", postalCodes: ["77570"], department: "77", departmentName: "Seine-et-Marne", population: 683 },
  { slug: "boulancourt", name: "Boulancourt", postalCodes: ["77760"], department: "77", departmentName: "Seine-et-Marne", population: 418 },
  { slug: "bouleurs", name: "Bouleurs", postalCodes: ["77580"], department: "77", departmentName: "Seine-et-Marne", population: 1456 },
  { slug: "bourron-marlotte", name: "Bourron-Marlotte", postalCodes: ["77780"], department: "77", departmentName: "Seine-et-Marne", population: 2934 },
  { slug: "boutigny", name: "Boutigny", postalCodes: ["77470"], department: "77", departmentName: "Seine-et-Marne", population: 1203 },
  { slug: "bransles", name: "Bransles", postalCodes: ["77620"], department: "77", departmentName: "Seine-et-Marne", population: 769 },
  { slug: "bray-sur-seine", name: "Bray-sur-Seine", postalCodes: ["77480"], department: "77", departmentName: "Seine-et-Marne", population: 2534 },
  { slug: "breau", name: "Bréau", postalCodes: ["77720"], department: "77", departmentName: "Seine-et-Marne", population: 213 },
  { slug: "brie-comte-robert", name: "Brie-Comte-Robert", postalCodes: ["77170"], department: "77", departmentName: "Seine-et-Marne", population: 18456 },
  { slug: "brou-sur-chantereine", name: "Brou-sur-Chantereine", postalCodes: ["77177"], department: "77", departmentName: "Seine-et-Marne", population: 4678 },
  { slug: "burcy", name: "Burcy", postalCodes: ["77890"], department: "77", departmentName: "Seine-et-Marne", population: 385 },
  { slug: "bussieres", name: "Bussières", postalCodes: ["77750"], department: "77", departmentName: "Seine-et-Marne", population: 612 },
  { slug: "bussy-saint-martin", name: "Bussy-Saint-Martin", postalCodes: ["77600"], department: "77", departmentName: "Seine-et-Marne", population: 1023 },
  { slug: "cannes-ecluse", name: "Cannes-Écluse", postalCodes: ["77130"], department: "77", departmentName: "Seine-et-Marne", population: 3145 },
  { slug: "carnetin", name: "Carnetin", postalCodes: ["77400"], department: "77", departmentName: "Seine-et-Marne", population: 654 },
  { slug: "cely", name: "Cély", postalCodes: ["77930"], department: "77", departmentName: "Seine-et-Marne", population: 1234 },
  { slug: "cerneux", name: "Cerneux", postalCodes: ["77320"], department: "77", departmentName: "Seine-et-Marne", population: 234 },
  { slug: "cesson", name: "Cesson", postalCodes: ["77240"], department: "77", departmentName: "Seine-et-Marne", population: 9876 },
  { slug: "chailly-en-biere", name: "Chailly-en-Bière", postalCodes: ["77930"], department: "77", departmentName: "Seine-et-Marne", population: 2156 },
  { slug: "chalifert", name: "Chalifert", postalCodes: ["77144"], department: "77", departmentName: "Seine-et-Marne", population: 1234 },
  { slug: "chalmaison", name: "Chalmaison", postalCodes: ["77650"], department: "77", departmentName: "Seine-et-Marne", population: 324 },
  { slug: "chambry", name: "Chambry", postalCodes: ["77910"], department: "77", departmentName: "Seine-et-Marne", population: 567 },
  { slug: "chamigny", name: "Chamigny", postalCodes: ["77260"], department: "77", departmentName: "Seine-et-Marne", population: 1567 },
  { slug: "champagne-sur-seine", name: "Champagne-sur-Seine", postalCodes: ["77430"], department: "77", departmentName: "Seine-et-Marne", population: 6789 },
  { slug: "champcenest", name: "Champcenest", postalCodes: ["77560"], department: "77", departmentName: "Seine-et-Marne", population: 456 },
  { slug: "champdeuil", name: "Champdeuil", postalCodes: ["77390"], department: "77", departmentName: "Seine-et-Marne", population: 312 },
  { slug: "champeaux", name: "Champeaux", postalCodes: ["77720"], department: "77", departmentName: "Seine-et-Marne", population: 876 },
  { slug: "champs-sur-marne", name: "Champs-sur-Marne", postalCodes: ["77420"], department: "77", departmentName: "Seine-et-Marne", population: 26345 },
  { slug: "changis-sur-marne", name: "Changis-sur-Marne", postalCodes: ["77660"], department: "77", departmentName: "Seine-et-Marne", population: 1867 },
  { slug: "chanteloup-en-brie", name: "Chanteloup-en-Brie", postalCodes: ["77600"], department: "77", departmentName: "Seine-et-Marne", population: 2345 },
  { slug: "la-chapelle-gauthier", name: "La Chapelle-Gauthier", postalCodes: ["77720"], department: "77", departmentName: "Seine-et-Marne", population: 1456 },
  { slug: "la-chapelle-iger", name: "La Chapelle-Iger", postalCodes: ["77540"], department: "77", departmentName: "Seine-et-Marne", population: 234 },
  { slug: "la-chapelle-la-reine", name: "La Chapelle-la-Reine", postalCodes: ["77760"], department: "77", departmentName: "Seine-et-Marne", population: 2678 },
  { slug: "la-chapelle-moutils", name: "La Chapelle-Moutils", postalCodes: ["77320"], department: "77", departmentName: "Seine-et-Marne", population: 178 },
  { slug: "la-chapelle-rablais", name: "La Chapelle-Rablais", postalCodes: ["77370"], department: "77", departmentName: "Seine-et-Marne", population: 567 },
  { slug: "la-chapelle-saint-sulpice", name: "La Chapelle-Saint-Sulpice", postalCodes: ["77160"], department: "77", departmentName: "Seine-et-Marne", population: 345 },
  { slug: "charmentray", name: "Charmentray", postalCodes: ["77410"], department: "77", departmentName: "Seine-et-Marne", population: 789 },
  { slug: "charny", name: "Charny", postalCodes: ["77410"], department: "77", departmentName: "Seine-et-Marne", population: 567 },
  { slug: "chartrettes", name: "Chartrettes", postalCodes: ["77590"], department: "77", departmentName: "Seine-et-Marne", population: 2567 },
  { slug: "chateau-landon", name: "Château-Landon", postalCodes: ["77570"], department: "77", departmentName: "Seine-et-Marne", population: 3456 },
  { slug: "chatenay-sur-seine", name: "Châtenay-sur-Seine", postalCodes: ["77126"], department: "77", departmentName: "Seine-et-Marne", population: 567 },
  { slug: "chatenoy", name: "Châtenoy", postalCodes: ["77167"], department: "77", departmentName: "Seine-et-Marne", population: 234 },
  { slug: "chatillon-la-borde", name: "Châtillon-la-Borde", postalCodes: ["77820"], department: "77", departmentName: "Seine-et-Marne", population: 345 },
  { slug: "chatres", name: "Châtres", postalCodes: ["77610"], department: "77", departmentName: "Seine-et-Marne", population: 567 },
  { slug: "chauconin-neufmontiers", name: "Chauconin-Neufmontiers", postalCodes: ["77124"], department: "77", departmentName: "Seine-et-Marne", population: 2345 },
  { slug: "chauffry", name: "Chauffry", postalCodes: ["77169"], department: "77", departmentName: "Seine-et-Marne", population: 890 },
  { slug: "chaumes-en-brie", name: "Chaumes-en-Brie", postalCodes: ["77390"], department: "77", departmentName: "Seine-et-Marne", population: 3234 },
  { slug: "chelles", name: "Chelles", postalCodes: ["77500"], department: "77", departmentName: "Seine-et-Marne", population: 55234 },
  { slug: "chenoise", name: "Chenoise", postalCodes: ["77160"], department: "77", departmentName: "Seine-et-Marne", population: 1234 },
  { slug: "chenou", name: "Chenou", postalCodes: ["77570"], department: "77", departmentName: "Seine-et-Marne", population: 456 },
  { slug: "chessy", name: "Chessy", postalCodes: ["77700"], department: "77", departmentName: "Seine-et-Marne", population: 6789 },
  { slug: "chevrainvilliers", name: "Chevrainvilliers", postalCodes: ["77760"], department: "77", departmentName: "Seine-et-Marne", population: 345 },
  { slug: "chevru", name: "Chevru", postalCodes: ["77320"], department: "77", departmentName: "Seine-et-Marne", population: 678 },
  { slug: "chevry-cossigny", name: "Chevry-Cossigny", postalCodes: ["77173"], department: "77", departmentName: "Seine-et-Marne", population: 2345 },
  { slug: "chevry-en-sereine", name: "Chevry-en-Sereine", postalCodes: ["77710"], department: "77", departmentName: "Seine-et-Marne", population: 234 },
  { slug: "choisy-en-brie", name: "Choisy-en-Brie", postalCodes: ["77320"], department: "77", departmentName: "Seine-et-Marne", population: 1567 },
  { slug: "citry", name: "Citry", postalCodes: ["77730"], department: "77", departmentName: "Seine-et-Marne", population: 456 },
  { slug: "claye-souilly", name: "Claye-Souilly", postalCodes: ["77410"], department: "77", departmentName: "Seine-et-Marne", population: 12456 },
  { slug: "clos-fontaine", name: "Clos-Fontaine", postalCodes: ["77370"], department: "77", departmentName: "Seine-et-Marne", population: 234 },
  { slug: "cocherel", name: "Cocherel", postalCodes: ["77440"], department: "77", departmentName: "Seine-et-Marne", population: 345 },
  { slug: "collegien", name: "Collégien", postalCodes: ["77090"], department: "77", departmentName: "Seine-et-Marne", population: 3567 },
  { slug: "compans", name: "Compans", postalCodes: ["77290"], department: "77", departmentName: "Seine-et-Marne", population: 987 },
  { slug: "conches-sur-gondoire", name: "Conches-sur-Gondoire", postalCodes: ["77600"], department: "77", departmentName: "Seine-et-Marne", population: 2345 },
  { slug: "conde-sainte-libiaire", name: "Condé-Sainte-Libiaire", postalCodes: ["77450"], department: "77", departmentName: "Seine-et-Marne", population: 1678 },
  { slug: "congis-sur-therouanne", name: "Congis-sur-Thérouanne", postalCodes: ["77440"], department: "77", departmentName: "Seine-et-Marne", population: 1234 },
  { slug: "coubert", name: "Coubert", postalCodes: ["77170"], department: "77", departmentName: "Seine-et-Marne", population: 2567 },
  { slug: "couilly-pont-aux-dames", name: "Couilly-Pont-aux-Dames", postalCodes: ["77860"], department: "77", departmentName: "Seine-et-Marne", population: 2789 },
  { slug: "coulombs-en-valois", name: "Coulombs-en-Valois", postalCodes: ["77840"], department: "77", departmentName: "Seine-et-Marne", population: 1234 },
  { slug: "coulommes", name: "Coulommes", postalCodes: ["77580"], department: "77", departmentName: "Seine-et-Marne", population: 1567 },
  { slug: "coulommiers", name: "Coulommiers", postalCodes: ["77120"], department: "77", departmentName: "Seine-et-Marne", population: 15234 },
  { slug: "coupvray", name: "Coupvray", postalCodes: ["77700"], department: "77", departmentName: "Seine-et-Marne", population: 3456 },
  { slug: "courpalay", name: "Courpalay", postalCodes: ["77540"], department: "77", departmentName: "Seine-et-Marne", population: 678 },
  { slug: "courquetaine", name: "Courquetaine", postalCodes: ["77390"], department: "77", departmentName: "Seine-et-Marne", population: 567 },
  { slug: "courtacon", name: "Courtacon", postalCodes: ["77560"], department: "77", departmentName: "Seine-et-Marne", population: 178 },
  { slug: "courtomer", name: "Courtomer", postalCodes: ["77390"], department: "77", departmentName: "Seine-et-Marne", population: 890 },
  { slug: "courtry", name: "Courtry", postalCodes: ["77181"], department: "77", departmentName: "Seine-et-Marne", population: 6789 },
  { slug: "coutencon", name: "Coutencon", postalCodes: ["77154"], department: "77", departmentName: "Seine-et-Marne", population: 123 },
  { slug: "coutevroult", name: "Coutevroult", postalCodes: ["77580"], department: "77", departmentName: "Seine-et-Marne", population: 1234 },
  { slug: "crecy-la-chapelle", name: "Crécy-la-Chapelle", postalCodes: ["77580"], department: "77", departmentName: "Seine-et-Marne", population: 5234 },
  { slug: "cregy-les-meaux", name: "Crégy-lès-Meaux", postalCodes: ["77124"], department: "77", departmentName: "Seine-et-Marne", population: 4567 },
  { slug: "croissy-beaubourg", name: "Croissy-Beaubourg", postalCodes: ["77183"], department: "77", departmentName: "Seine-et-Marne", population: 2678 },
  { slug: "la-croix-en-brie", name: "La Croix-en-Brie", postalCodes: ["77370"], department: "77", departmentName: "Seine-et-Marne", population: 567 },
  { slug: "crouy-sur-ourcq", name: "Crouy-sur-Ourcq", postalCodes: ["77840"], department: "77", departmentName: "Seine-et-Marne", population: 2345 },
  { slug: "cuisy", name: "Cuisy", postalCodes: ["77165"], department: "77", departmentName: "Seine-et-Marne", population: 678 },
  { slug: "dammarie-les-lys", name: "Dammarie-lès-Lys", postalCodes: ["77190"], department: "77", departmentName: "Seine-et-Marne", population: 23456 },
  { slug: "dammartin-en-goele", name: "Dammartin-en-Goële", postalCodes: ["77230"], department: "77", departmentName: "Seine-et-Marne", population: 8234 },
  { slug: "dammartin-sur-tigeaux", name: "Dammartin-sur-Tigeaux", postalCodes: ["77163"], department: "77", departmentName: "Seine-et-Marne", population: 1234 },
  { slug: "dampmart", name: "Dampmart", postalCodes: ["77400"], department: "77", departmentName: "Seine-et-Marne", population: 3456 },
  { slug: "darvault", name: "Darvault", postalCodes: ["77140"], department: "77", departmentName: "Seine-et-Marne", population: 1234 },
  { slug: "dhuisy", name: "Dhuisy", postalCodes: ["77440"], department: "77", departmentName: "Seine-et-Marne", population: 678 },
  { slug: "donnemarie-dontilly", name: "Donnemarie-Dontilly", postalCodes: ["77520"], department: "77", departmentName: "Seine-et-Marne", population: 2567 },
  { slug: "doue", name: "Doue", postalCodes: ["77510"], department: "77", departmentName: "Seine-et-Marne", population: 1234 },
  { slug: "douy-la-ramee", name: "Douy-la-Ramée", postalCodes: ["77139"], department: "77", departmentName: "Seine-et-Marne", population: 567 },
  { slug: "ecuelles", name: "Écuelles", postalCodes: ["77250"], department: "77", departmentName: "Seine-et-Marne", population: 2345 },
  { slug: "egligny", name: "Égligny", postalCodes: ["77126"], department: "77", departmentName: "Seine-et-Marne", population: 234 },
  { slug: "egreville", name: "Égreville", postalCodes: ["77620"], department: "77", departmentName: "Seine-et-Marne", population: 2345 },
  { slug: "emerainville", name: "Émerainville", postalCodes: ["77184"], department: "77", departmentName: "Seine-et-Marne", population: 7890 },
  { slug: "esbly", name: "Esbly", postalCodes: ["77450"], department: "77", departmentName: "Seine-et-Marne", population: 6234 },
  { slug: "esmans", name: "Esmans", postalCodes: ["77940"], department: "77", departmentName: "Seine-et-Marne", population: 567 },
  { slug: "etrepilly", name: "Étrépilly", postalCodes: ["77139"], department: "77", departmentName: "Seine-et-Marne", population: 678 },
  { slug: "everly", name: "Éverly", postalCodes: ["77157"], department: "77", departmentName: "Seine-et-Marne", population: 345 },
  { slug: "evry-gregy-sur-yerre", name: "Évry-Grégy-sur-Yerre", postalCodes: ["77166"], department: "77", departmentName: "Seine-et-Marne", population: 3456 },
  { slug: "faremoutiers", name: "Faremoutiers", postalCodes: ["77515"], department: "77", departmentName: "Seine-et-Marne", population: 2345 },
  { slug: "la-ferte-gaucher", name: "La Ferté-Gaucher", postalCodes: ["77320"], department: "77", departmentName: "Seine-et-Marne", population: 4567 },
  { slug: "la-ferte-sous-jouarre", name: "La Ferté-sous-Jouarre", postalCodes: ["77260"], department: "77", departmentName: "Seine-et-Marne", population: 10234 },
  { slug: "ferolles-attilly", name: "Férolles-Attilly", postalCodes: ["77150"], department: "77", departmentName: "Seine-et-Marne", population: 2345 },
  { slug: "ferrières-en-brie", name: "Ferrières-en-Brie", postalCodes: ["77164"], department: "77", departmentName: "Seine-et-Marne", population: 2678 },
  { slug: "flagy", name: "Flagy", postalCodes: ["77940"], department: "77", departmentName: "Seine-et-Marne", population: 567 },
  { slug: "fleury-en-biere", name: "Fleury-en-Bière", postalCodes: ["77930"], department: "77", departmentName: "Seine-et-Marne", population: 678 },
  { slug: "fontainebleau", name: "Fontainebleau", postalCodes: ["77300"], department: "77", departmentName: "Seine-et-Marne", population: 14567 },
  { slug: "fontaine-fourches", name: "Fontaine-Fourches", postalCodes: ["77480"], department: "77", departmentName: "Seine-et-Marne", population: 234 },
  { slug: "fontaine-le-port", name: "Fontaine-le-Port", postalCodes: ["77590"], department: "77", departmentName: "Seine-et-Marne", population: 987 },
  { slug: "fontenailles", name: "Fontenailles", postalCodes: ["77370"], department: "77", departmentName: "Seine-et-Marne", population: 1234 },
  { slug: "fontenay-trésigny", name: "Fontenay-Trésigny", postalCodes: ["77610"], department: "77", departmentName: "Seine-et-Marne", population: 5678 },
  { slug: "forfry", name: "Forfry", postalCodes: ["77165"], department: "77", departmentName: "Seine-et-Marne", population: 345 },
  { slug: "forges", name: "Forges", postalCodes: ["77130"], department: "77", departmentName: "Seine-et-Marne", population: 567 },
  { slug: "fouju", name: "Fouju", postalCodes: ["77390"], department: "77", departmentName: "Seine-et-Marne", population: 345 },
  { slug: "fresnes-sur-marne", name: "Fresnes-sur-Marne", postalCodes: ["77410"], department: "77", departmentName: "Seine-et-Marne", population: 1234 },
  { slug: "fretoy", name: "Frétoy", postalCodes: ["77320"], department: "77", departmentName: "Seine-et-Marne", population: 123 },
  { slug: "fromont", name: "Fromont", postalCodes: ["77760"], department: "77", departmentName: "Seine-et-Marne", population: 234 },
  { slug: "fublaines", name: "Fublaines", postalCodes: ["77470"], department: "77", departmentName: "Seine-et-Marne", population: 345 },
  { slug: "gastins", name: "Gastins", postalCodes: ["77370"], department: "77", departmentName: "Seine-et-Marne", population: 567 },
  { slug: "gatinais-val-de-loing", name: "Gâtinais-Val-de-Loing", postalCodes: ["77167"], department: "77", departmentName: "Seine-et-Marne", population: 234 },
  { slug: "germigny-l-eveque", name: "Germigny-l'Évêque", postalCodes: ["77910"], department: "77", departmentName: "Seine-et-Marne", population: 1456 },
  { slug: "germigny-sous-coulombs", name: "Germigny-sous-Coulombs", postalCodes: ["77840"], department: "77", departmentName: "Seine-et-Marne", population: 567 },
  { slug: "giremoutiers", name: "Giremoutiers", postalCodes: ["77120"], department: "77", departmentName: "Seine-et-Marne", population: 234 },
  { slug: "gouvernes", name: "Gouvernes", postalCodes: ["77400"], department: "77", departmentName: "Seine-et-Marne", population: 1234 },
  { slug: "grandpuits-bailly-carrois", name: "Grandpuits-Bailly-Carrois", postalCodes: ["77720"], department: "77", departmentName: "Seine-et-Marne", population: 987 },
  { slug: "gretz-armainvilliers", name: "Gretz-Armainvilliers", postalCodes: ["77220"], department: "77", departmentName: "Seine-et-Marne", population: 8234 },
  { slug: "grisy-sur-seine", name: "Grisy-sur-Seine", postalCodes: ["77480"], department: "77", departmentName: "Seine-et-Marne", population: 345 },
  { slug: "grisy-suisnes", name: "Grisy-Suisnes", postalCodes: ["77166"], department: "77", departmentName: "Seine-et-Marne", population: 2567 },
  { slug: "guerard", name: "Guérard", postalCodes: ["77580"], department: "77", departmentName: "Seine-et-Marne", population: 2345 },
  { slug: "guercheville", name: "Guercheville", postalCodes: ["77760"], department: "77", departmentName: "Seine-et-Marne", population: 234 },
  { slug: "guignes", name: "Guignes", postalCodes: ["77390"], department: "77", departmentName: "Seine-et-Marne", population: 3456 },
  { slug: "gurcy-le-chatel", name: "Gurcy-le-Châtel", postalCodes: ["77520"], department: "77", departmentName: "Seine-et-Marne", population: 678 },
  { slug: "hautefeuille", name: "Hautefeuille", postalCodes: ["77515"], department: "77", departmentName: "Seine-et-Marne", population: 567 },
  { slug: "hericy", name: "Héricy", postalCodes: ["77850"], department: "77", departmentName: "Seine-et-Marne", population: 2789 },
  { slug: "herme", name: "Hermé", postalCodes: ["77114"], department: "77", departmentName: "Seine-et-Marne", population: 567 },
  { slug: "hondevilliers", name: "Hondevilliers", postalCodes: ["77510"], department: "77", departmentName: "Seine-et-Marne", population: 234 },
  { slug: "ichy", name: "Ichy", postalCodes: ["77890"], department: "77", departmentName: "Seine-et-Marne", population: 234 },
  { slug: "isles-les-meldeuses", name: "Isles-lès-Meldeuses", postalCodes: ["77440"], department: "77", departmentName: "Seine-et-Marne", population: 678 },
  { slug: "jablines", name: "Jablines", postalCodes: ["77450"], department: "77", departmentName: "Seine-et-Marne", population: 678 },
  { slug: "jaignes", name: "Jaignes", postalCodes: ["77440"], department: "77", departmentName: "Seine-et-Marne", population: 567 },
  { slug: "jaulnes", name: "Jaulnes", postalCodes: ["77480"], department: "77", departmentName: "Seine-et-Marne", population: 345 },
  { slug: "jouarre", name: "Jouarre", postalCodes: ["77640"], department: "77", departmentName: "Seine-et-Marne", population: 4234 },
  { slug: "jouy-le-chatel", name: "Jouy-le-Châtel", postalCodes: ["77970"], department: "77", departmentName: "Seine-et-Marne", population: 1567 },
  { slug: "jouy-sur-morin", name: "Jouy-sur-Morin", postalCodes: ["77320"], department: "77", departmentName: "Seine-et-Marne", population: 2345 },
  { slug: "juilly", name: "Juilly", postalCodes: ["77230"], department: "77", departmentName: "Seine-et-Marne", population: 2234 },
  { slug: "jossigny", name: "Jossigny", postalCodes: ["77600"], department: "77", departmentName: "Seine-et-Marne", population: 678 },
];

// Yvelines (78) - Communes complémentaires
const yvelinesExtra: CityData[] = [
  { slug: "ablis", name: "Ablis", postalCodes: ["78660"], department: "78", departmentName: "Yvelines", population: 3567 },
  { slug: "achères", name: "Achères", postalCodes: ["78260"], department: "78", departmentName: "Yvelines", population: 21234 },
  { slug: "adainville", name: "Adainville", postalCodes: ["78113"], department: "78", departmentName: "Yvelines", population: 567 },
  { slug: "aigremont", name: "Aigremont", postalCodes: ["78240"], department: "78", departmentName: "Yvelines", population: 1234 },
  { slug: "allainville", name: "Allainville", postalCodes: ["78660"], department: "78", departmentName: "Yvelines", population: 234 },
  { slug: "andelu", name: "Andelu", postalCodes: ["78770"], department: "78", departmentName: "Yvelines", population: 567 },
  { slug: "andresy", name: "Andrésy", postalCodes: ["78570"], department: "78", departmentName: "Yvelines", population: 13567 },
  { slug: "arnouville-les-mantes", name: "Arnouville-lès-Mantes", postalCodes: ["78790"], department: "78", departmentName: "Yvelines", population: 234 },
  { slug: "auffreville-brasseuil", name: "Auffreville-Brasseuil", postalCodes: ["78930"], department: "78", departmentName: "Yvelines", population: 345 },
  { slug: "aulnay-sur-mauldre", name: "Aulnay-sur-Mauldre", postalCodes: ["78126"], department: "78", departmentName: "Yvelines", population: 1234 },
  { slug: "auteuil", name: "Auteuil", postalCodes: ["78770"], department: "78", departmentName: "Yvelines", population: 987 },
  { slug: "autouillet", name: "Autouillet", postalCodes: ["78770"], department: "78", departmentName: "Yvelines", population: 567 },
  { slug: "bailly", name: "Bailly", postalCodes: ["78870"], department: "78", departmentName: "Yvelines", population: 4234 },
  { slug: "bazainville", name: "Bazainville", postalCodes: ["78550"], department: "78", departmentName: "Yvelines", population: 1456 },
  { slug: "bazemont", name: "Bazemont", postalCodes: ["78580"], department: "78", departmentName: "Yvelines", population: 1234 },
  { slug: "behoust", name: "Béhoust", postalCodes: ["78910"], department: "78", departmentName: "Yvelines", population: 567 },
  { slug: "bennecourt", name: "Bennecourt", postalCodes: ["78270"], department: "78", departmentName: "Yvelines", population: 1890 },
  { slug: "beynes", name: "Beynes", postalCodes: ["78650"], department: "78", departmentName: "Yvelines", population: 8234 },
  { slug: "blaru", name: "Blaru", postalCodes: ["78270"], department: "78", departmentName: "Yvelines", population: 567 },
  { slug: "boinville-en-mantois", name: "Boinville-en-Mantois", postalCodes: ["78930"], department: "78", departmentName: "Yvelines", population: 234 },
  { slug: "boinville-le-gaillard", name: "Boinville-le-Gaillard", postalCodes: ["78660"], department: "78", departmentName: "Yvelines", population: 234 },
  { slug: "boinvilliers", name: "Boinvilliers", postalCodes: ["78200"], department: "78", departmentName: "Yvelines", population: 345 },
  { slug: "bois-d-arcy", name: "Bois-d'Arcy", postalCodes: ["78390"], department: "78", departmentName: "Yvelines", population: 14567 },
  { slug: "boissets", name: "Boissets", postalCodes: ["78910"], department: "78", departmentName: "Yvelines", population: 234 },
  { slug: "boissy-mauvoisin", name: "Boissy-Mauvoisin", postalCodes: ["78200"], department: "78", departmentName: "Yvelines", population: 678 },
  { slug: "boissy-sans-avoir", name: "Boissy-sans-Avoir", postalCodes: ["78490"], department: "78", departmentName: "Yvelines", population: 567 },
  { slug: "bonnelles", name: "Bonnelles", postalCodes: ["78830"], department: "78", departmentName: "Yvelines", population: 2345 },
  { slug: "bonnieres-sur-seine", name: "Bonnières-sur-Seine", postalCodes: ["78270"], department: "78", departmentName: "Yvelines", population: 4234 },
  { slug: "bouafle", name: "Bouafle", postalCodes: ["78410"], department: "78", departmentName: "Yvelines", population: 3456 },
  { slug: "bougival", name: "Bougival", postalCodes: ["78380"], department: "78", departmentName: "Yvelines", population: 8567 },
  { slug: "bourdonné", name: "Bourdonné", postalCodes: ["78113"], department: "78", departmentName: "Yvelines", population: 567 },
  { slug: "breuil-bois-robert", name: "Breuil-Bois-Robert", postalCodes: ["78930"], department: "78", departmentName: "Yvelines", population: 567 },
  { slug: "breval", name: "Bréval", postalCodes: ["78980"], department: "78", departmentName: "Yvelines", population: 2345 },
  { slug: "brueil-en-vexin", name: "Brueil-en-Vexin", postalCodes: ["78440"], department: "78", departmentName: "Yvelines", population: 567 },
  { slug: "buchelay", name: "Buchelay", postalCodes: ["78200"], department: "78", departmentName: "Yvelines", population: 2789 },
  { slug: "carrieres-sous-poissy", name: "Carrières-sous-Poissy", postalCodes: ["78955"], department: "78", departmentName: "Yvelines", population: 17234 },
  { slug: "carrieres-sur-seine", name: "Carrières-sur-Seine", postalCodes: ["78420"], department: "78", departmentName: "Yvelines", population: 16234 },
  { slug: "la-celle-les-bordes", name: "La Celle-les-Bordes", postalCodes: ["78720"], department: "78", departmentName: "Yvelines", population: 987 },
  { slug: "la-celle-saint-cloud", name: "La Celle-Saint-Cloud", postalCodes: ["78170"], department: "78", departmentName: "Yvelines", population: 22345 },
  { slug: "cernay-la-ville", name: "Cernay-la-Ville", postalCodes: ["78720"], department: "78", departmentName: "Yvelines", population: 1789 },
  { slug: "chambourcy", name: "Chambourcy", postalCodes: ["78240"], department: "78", departmentName: "Yvelines", population: 6234 },
  { slug: "chanteloup-les-vignes", name: "Chanteloup-les-Vignes", postalCodes: ["78570"], department: "78", departmentName: "Yvelines", population: 10234 },
  { slug: "chapet", name: "Chapet", postalCodes: ["78130"], department: "78", departmentName: "Yvelines", population: 1234 },
  { slug: "chateaufort", name: "Châteaufort", postalCodes: ["78117"], department: "78", departmentName: "Yvelines", population: 1567 },
  { slug: "chatou", name: "Chatou", postalCodes: ["78400"], department: "78", departmentName: "Yvelines", population: 32456 },
  { slug: "chaufour-les-bonnieres", name: "Chaufour-lès-Bonnières", postalCodes: ["78270"], department: "78", departmentName: "Yvelines", population: 234 },
  { slug: "chavenay", name: "Chavenay", postalCodes: ["78450"], department: "78", departmentName: "Yvelines", population: 2345 },
  { slug: "chevreuse", name: "Chevreuse", postalCodes: ["78460"], department: "78", departmentName: "Yvelines", population: 6234 },
  { slug: "choisel", name: "Choisel", postalCodes: ["78460"], department: "78", departmentName: "Yvelines", population: 567 },
  { slug: "civry-la-foret", name: "Civry-la-Forêt", postalCodes: ["78910"], department: "78", departmentName: "Yvelines", population: 234 },
  { slug: "clairefontaine-en-yvelines", name: "Clairefontaine-en-Yvelines", postalCodes: ["78120"], department: "78", departmentName: "Yvelines", population: 987 },
  { slug: "coignieres", name: "Coignières", postalCodes: ["78310"], department: "78", departmentName: "Yvelines", population: 4567 },
  { slug: "conde-sur-vesgre", name: "Condé-sur-Vesgre", postalCodes: ["78113"], department: "78", departmentName: "Yvelines", population: 1234 },
  { slug: "conflans-sainte-honorine", name: "Conflans-Sainte-Honorine", postalCodes: ["78700"], department: "78", departmentName: "Yvelines", population: 36234 },
  { slug: "courgent", name: "Courgent", postalCodes: ["78790"], department: "78", departmentName: "Yvelines", population: 234 },
  { slug: "cravent", name: "Cravent", postalCodes: ["78270"], department: "78", departmentName: "Yvelines", population: 234 },
  { slug: "crespieres", name: "Crespières", postalCodes: ["78121"], department: "78", departmentName: "Yvelines", population: 1789 },
  { slug: "croissy-sur-seine", name: "Croissy-sur-Seine", postalCodes: ["78290"], department: "78", departmentName: "Yvelines", population: 10456 },
  { slug: "dammartin-en-serve", name: "Dammartin-en-Serve", postalCodes: ["78111"], department: "78", departmentName: "Yvelines", population: 1234 },
  { slug: "dampierre-en-yvelines", name: "Dampierre-en-Yvelines", postalCodes: ["78720"], department: "78", departmentName: "Yvelines", population: 1234 },
  { slug: "dannemarie", name: "Dannemarie", postalCodes: ["78550"], department: "78", departmentName: "Yvelines", population: 234 },
  { slug: "davron", name: "Davron", postalCodes: ["78810"], department: "78", departmentName: "Yvelines", population: 567 },
  { slug: "ecquevilly", name: "Écquevilly", postalCodes: ["78920"], department: "78", departmentName: "Yvelines", population: 4234 },
  { slug: "elancourt", name: "Élancourt", postalCodes: ["78990"], department: "78", departmentName: "Yvelines", population: 26234 },
  { slug: "emance", name: "Émancé", postalCodes: ["78125"], department: "78", departmentName: "Yvelines", population: 987 },
  { slug: "epone", name: "Épône", postalCodes: ["78680"], department: "78", departmentName: "Yvelines", population: 7234 },
  { slug: "evecquemont", name: "Évecquemont", postalCodes: ["78740"], department: "78", departmentName: "Yvelines", population: 2345 },
  { slug: "la-falaise", name: "La Falaise", postalCodes: ["78410"], department: "78", departmentName: "Yvelines", population: 234 },
  { slug: "favrieux", name: "Favrieux", postalCodes: ["78200"], department: "78", departmentName: "Yvelines", population: 123 },
  { slug: "feucherolles", name: "Feucherolles", postalCodes: ["78810"], department: "78", departmentName: "Yvelines", population: 2567 },
  { slug: "flacourt", name: "Flacourt", postalCodes: ["78200"], department: "78", departmentName: "Yvelines", population: 234 },
  { slug: "flexanville", name: "Flexanville", postalCodes: ["78910"], department: "78", departmentName: "Yvelines", population: 567 },
  { slug: "flins-neuve-eglise", name: "Flins-Neuve-Église", postalCodes: ["78790"], department: "78", departmentName: "Yvelines", population: 123 },
  { slug: "flins-sur-seine", name: "Flins-sur-Seine", postalCodes: ["78410"], department: "78", departmentName: "Yvelines", population: 2345 },
  { slug: "follainville-dennemont", name: "Follainville-Dennemont", postalCodes: ["78520"], department: "78", departmentName: "Yvelines", population: 2456 },
  { slug: "fontenay-le-fleury", name: "Fontenay-le-Fleury", postalCodes: ["78330"], department: "78", departmentName: "Yvelines", population: 14234 },
  { slug: "fontenay-mauvoisin", name: "Fontenay-Mauvoisin", postalCodes: ["78200"], department: "78", departmentName: "Yvelines", population: 234 },
  { slug: "fontenay-saint-pere", name: "Fontenay-Saint-Père", postalCodes: ["78440"], department: "78", departmentName: "Yvelines", population: 678 },
  { slug: "fourqueux", name: "Fourqueux", postalCodes: ["78112"], department: "78", departmentName: "Yvelines", population: 4234 },
  { slug: "freneuse", name: "Freneuse", postalCodes: ["78840"], department: "78", departmentName: "Yvelines", population: 4567 },
  { slug: "gaillon-sur-montcient", name: "Gaillon-sur-Montcient", postalCodes: ["78250"], department: "78", departmentName: "Yvelines", population: 1234 },
  { slug: "galluis", name: "Galluis", postalCodes: ["78490"], department: "78", departmentName: "Yvelines", population: 1567 },
  { slug: "gambais", name: "Gambais", postalCodes: ["78950"], department: "78", departmentName: "Yvelines", population: 2789 },
  { slug: "gambaiseuil", name: "Gambaiseuil", postalCodes: ["78490"], department: "78", departmentName: "Yvelines", population: 345 },
  { slug: "garancieres", name: "Garancières", postalCodes: ["78890"], department: "78", departmentName: "Yvelines", population: 3234 },
  { slug: "gargenville", name: "Gargenville", postalCodes: ["78440"], department: "78", departmentName: "Yvelines", population: 7234 },
  { slug: "gazeran", name: "Gazeran", postalCodes: ["78125"], department: "78", departmentName: "Yvelines", population: 1567 },
  { slug: "gommecourt", name: "Gommecourt", postalCodes: ["78270"], department: "78", departmentName: "Yvelines", population: 567 },
  { slug: "goupillieres", name: "Goupillières", postalCodes: ["78770"], department: "78", departmentName: "Yvelines", population: 345 },
  { slug: "goussonville", name: "Goussonville", postalCodes: ["78930"], department: "78", departmentName: "Yvelines", population: 678 },
  { slug: "grandchamp", name: "Grandchamp", postalCodes: ["78113"], department: "78", departmentName: "Yvelines", population: 567 },
  { slug: "gressey", name: "Gressey", postalCodes: ["78550"], department: "78", departmentName: "Yvelines", population: 234 },
  { slug: "grosrouvre", name: "Grosrouvre", postalCodes: ["78490"], department: "78", departmentName: "Yvelines", population: 987 },
  { slug: "guernes", name: "Guernes", postalCodes: ["78520"], department: "78", departmentName: "Yvelines", population: 1234 },
  { slug: "guerville", name: "Guerville", postalCodes: ["78930"], department: "78", departmentName: "Yvelines", population: 2345 },
  { slug: "guitrancourt", name: "Guitrancourt", postalCodes: ["78440"], department: "78", departmentName: "Yvelines", population: 678 },
  { slug: "guyancourt", name: "Guyancourt", postalCodes: ["78280"], department: "78", departmentName: "Yvelines", population: 30234 },
  { slug: "hardricourt", name: "Hardricourt", postalCodes: ["78250"], department: "78", departmentName: "Yvelines", population: 1789 },
  { slug: "hargeville", name: "Hargeville", postalCodes: ["78790"], department: "78", departmentName: "Yvelines", population: 234 },
  { slug: "la-hauteville", name: "La Hauteville", postalCodes: ["78113"], department: "78", departmentName: "Yvelines", population: 234 },
  { slug: "les-essarts-le-roi", name: "Les Essarts-le-Roi", postalCodes: ["78690"], department: "78", departmentName: "Yvelines", population: 6789 },
  { slug: "houdan", name: "Houdan", postalCodes: ["78550"], department: "78", departmentName: "Yvelines", population: 3567 },
  { slug: "houilles", name: "Houilles", postalCodes: ["78800"], department: "78", departmentName: "Yvelines", population: 33234 },
  { slug: "issou", name: "Issou", postalCodes: ["78440"], department: "78", departmentName: "Yvelines", population: 4234 },
  { slug: "jambville", name: "Jambville", postalCodes: ["78440"], department: "78", departmentName: "Yvelines", population: 678 },
  { slug: "jouars-pontchartrain", name: "Jouars-Pontchartrain", postalCodes: ["78760"], department: "78", departmentName: "Yvelines", population: 5567 },
  { slug: "jouy-en-josas", name: "Jouy-en-Josas", postalCodes: ["78350"], department: "78", departmentName: "Yvelines", population: 8234 },
  { slug: "jouy-mauvoisin", name: "Jouy-Mauvoisin", postalCodes: ["78200"], department: "78", departmentName: "Yvelines", population: 345 },
  { slug: "juziers", name: "Juziers", postalCodes: ["78820"], department: "78", departmentName: "Yvelines", population: 4234 },
];

// Essonne (91) - Communes complémentaires
const essonneExtra: CityData[] = [
  { slug: "abbeville-la-riviere", name: "Abbéville-la-Rivière", postalCodes: ["91150"], department: "91", departmentName: "Essonne", population: 345 },
  { slug: "angerville", name: "Angerville", postalCodes: ["91670"], department: "91", departmentName: "Essonne", population: 4234 },
  { slug: "angervilliers", name: "Angervilliers", postalCodes: ["91470"], department: "91", departmentName: "Essonne", population: 1234 },
  { slug: "arpajon", name: "Arpajon", postalCodes: ["91290"], department: "91", departmentName: "Essonne", population: 11234 },
  { slug: "arrancourt", name: "Arrancourt", postalCodes: ["91690"], department: "91", departmentName: "Essonne", population: 123 },
  { slug: "authon-la-plaine", name: "Authon-la-Plaine", postalCodes: ["91410"], department: "91", departmentName: "Essonne", population: 567 },
  { slug: "auvernaux", name: "Auvernaux", postalCodes: ["91830"], department: "91", departmentName: "Essonne", population: 1234 },
  { slug: "auvers-saint-georges", name: "Auvers-Saint-Georges", postalCodes: ["91580"], department: "91", departmentName: "Essonne", population: 1789 },
  { slug: "avrainville", name: "Avrainville", postalCodes: ["91630"], department: "91", departmentName: "Essonne", population: 678 },
  { slug: "ballainvilliers", name: "Ballainvilliers", postalCodes: ["91160"], department: "91", departmentName: "Essonne", population: 4567 },
  { slug: "ballancourt-sur-essonne", name: "Ballancourt-sur-Essonne", postalCodes: ["91610"], department: "91", departmentName: "Essonne", population: 8234 },
  { slug: "baulne", name: "Baulne", postalCodes: ["91590"], department: "91", departmentName: "Essonne", population: 1234 },
  { slug: "bievres", name: "Bièvres", postalCodes: ["91570"], department: "91", departmentName: "Essonne", population: 5234 },
  { slug: "blandy", name: "Blandy", postalCodes: ["91150"], department: "91", departmentName: "Essonne", population: 234 },
  { slug: "boissy-la-riviere", name: "Boissy-la-Rivière", postalCodes: ["91690"], department: "91", departmentName: "Essonne", population: 456 },
  { slug: "boissy-le-cutte", name: "Boissy-le-Cutté", postalCodes: ["91590"], department: "91", departmentName: "Essonne", population: 789 },
  { slug: "boissy-le-sec", name: "Boissy-le-Sec", postalCodes: ["91870"], department: "91", departmentName: "Essonne", population: 567 },
  { slug: "boissy-sous-saint-yon", name: "Boissy-sous-Saint-Yon", postalCodes: ["91790"], department: "91", departmentName: "Essonne", population: 4234 },
  { slug: "bondoufle", name: "Bondoufle", postalCodes: ["91070"], department: "91", departmentName: "Essonne", population: 10234 },
  { slug: "bouray-sur-juine", name: "Bouray-sur-Juine", postalCodes: ["91850"], department: "91", departmentName: "Essonne", population: 2345 },
  { slug: "boussy-saint-antoine", name: "Boussy-Saint-Antoine", postalCodes: ["91800"], department: "91", departmentName: "Essonne", population: 8234 },
  { slug: "boutervilliers", name: "Boutervilliers", postalCodes: ["91150"], department: "91", departmentName: "Essonne", population: 234 },
  { slug: "boutigny-sur-essonne", name: "Boutigny-sur-Essonne", postalCodes: ["91820"], department: "91", departmentName: "Essonne", population: 3234 },
  { slug: "bouville", name: "Bouville", postalCodes: ["91880"], department: "91", departmentName: "Essonne", population: 678 },
  { slug: "breuillet", name: "Breuillet", postalCodes: ["91650"], department: "91", departmentName: "Essonne", population: 8567 },
  { slug: "breux-jouy", name: "Breux-Jouy", postalCodes: ["91650"], department: "91", departmentName: "Essonne", population: 2345 },
  { slug: "brieres-les-scelles", name: "Brières-les-Scellés", postalCodes: ["91150"], department: "91", departmentName: "Essonne", population: 1789 },
  { slug: "briis-sous-forges", name: "Briis-sous-Forges", postalCodes: ["91640"], department: "91", departmentName: "Essonne", population: 3567 },
  { slug: "brouy", name: "Brouy", postalCodes: ["91150"], department: "91", departmentName: "Essonne", population: 456 },
  { slug: "brunoy", name: "Brunoy", postalCodes: ["91800"], department: "91", departmentName: "Essonne", population: 26234 },
  { slug: "bruyeres-le-chatel", name: "Bruyères-le-Châtel", postalCodes: ["91680"], department: "91", departmentName: "Essonne", population: 3678 },
  { slug: "buno-bonnevaux", name: "Buno-Bonnevaux", postalCodes: ["91720"], department: "91", departmentName: "Essonne", population: 567 },
  { slug: "cerny", name: "Cerny", postalCodes: ["91590"], department: "91", departmentName: "Essonne", population: 2567 },
  { slug: "chailly-chambertin", name: "Chalo-Saint-Mars", postalCodes: ["91780"], department: "91", departmentName: "Essonne", population: 1456 },
  { slug: "chamarande", name: "Chamarande", postalCodes: ["91730"], department: "91", departmentName: "Essonne", population: 1234 },
  { slug: "champcueil", name: "Champcueil", postalCodes: ["91750"], department: "91", departmentName: "Essonne", population: 2789 },
  { slug: "champlan", name: "Champlan", postalCodes: ["91160"], department: "91", departmentName: "Essonne", population: 2789 },
  { slug: "cheptainville", name: "Cheptainville", postalCodes: ["91630"], department: "91", departmentName: "Essonne", population: 2345 },
  { slug: "chevannes", name: "Chevannes", postalCodes: ["91750"], department: "91", departmentName: "Essonne", population: 2234 },
  { slug: "chilly-mazarin", name: "Chilly-Mazarin", postalCodes: ["91380"], department: "91", departmentName: "Essonne", population: 20234 },
  { slug: "congerville-thionville", name: "Congerville-Thionville", postalCodes: ["91740"], department: "91", departmentName: "Essonne", population: 567 },
  { slug: "corbeil-essonnes", name: "Corbeil-Essonnes", postalCodes: ["91100"], department: "91", departmentName: "Essonne", population: 52234 },
  { slug: "corbreuse", name: "Corbreuse", postalCodes: ["91410"], department: "91", departmentName: "Essonne", population: 789 },
  { slug: "courances", name: "Courances", postalCodes: ["91490"], department: "91", departmentName: "Essonne", population: 567 },
  { slug: "courcouronnes", name: "Courcouronnes", postalCodes: ["91080"], department: "91", departmentName: "Essonne", population: 16234 },
  { slug: "courdimanche-sur-essonne", name: "Courdimanche-sur-Essonne", postalCodes: ["91720"], department: "91", departmentName: "Essonne", population: 234 },
  { slug: "courson-monteloup", name: "Courson-Monteloup", postalCodes: ["91680"], department: "91", departmentName: "Essonne", population: 678 },
  { slug: "crosne", name: "Crosne", postalCodes: ["91560"], department: "91", departmentName: "Essonne", population: 10234 },
  { slug: "d-huison-longueville", name: "D'Huison-Longueville", postalCodes: ["91590"], department: "91", departmentName: "Essonne", population: 1234 },
  { slug: "dannemois", name: "Dannemois", postalCodes: ["91490"], department: "91", departmentName: "Essonne", population: 678 },
  { slug: "dourdan", name: "Dourdan", postalCodes: ["91410"], department: "91", departmentName: "Essonne", population: 11234 },
  { slug: "draveil", name: "Draveil", postalCodes: ["91210"], department: "91", departmentName: "Essonne", population: 30234 },
  { slug: "echarcon", name: "Écharcon", postalCodes: ["91540"], department: "91", departmentName: "Essonne", population: 1456 },
  { slug: "egly", name: "Égly", postalCodes: ["91520"], department: "91", departmentName: "Essonne", population: 5678 },
  { slug: "epinay-sous-senart", name: "Épinay-sous-Sénart", postalCodes: ["91860"], department: "91", departmentName: "Essonne", population: 13234 },
  { slug: "epinay-sur-orge", name: "Épinay-sur-Orge", postalCodes: ["91360"], department: "91", departmentName: "Essonne", population: 11234 },
  { slug: "estouches", name: "Estouches", postalCodes: ["91660"], department: "91", departmentName: "Essonne", population: 234 },
  { slug: "etampes", name: "Étampes", postalCodes: ["91150"], department: "91", departmentName: "Essonne", population: 24234 },
  { slug: "etiolles", name: "Étiolles", postalCodes: ["91450"], department: "91", departmentName: "Essonne", population: 3456 },
  { slug: "etrechy", name: "Étréchy", postalCodes: ["91580"], department: "91", departmentName: "Essonne", population: 6789 },
  { slug: "evry-courcouronnes", name: "Évry-Courcouronnes", postalCodes: ["91000", "91080"], department: "91", departmentName: "Essonne", population: 67234 },
  { slug: "fleury-merogis", name: "Fleury-Mérogis", postalCodes: ["91700"], department: "91", departmentName: "Essonne", population: 9234 },
  { slug: "fontaine-la-riviere", name: "Fontaine-la-Rivière", postalCodes: ["91690"], department: "91", departmentName: "Essonne", population: 234 },
  { slug: "fontenay-le-vicomte", name: "Fontenay-le-Vicomte", postalCodes: ["91540"], department: "91", departmentName: "Essonne", population: 1789 },
  { slug: "fontenay-les-briis", name: "Fontenay-lès-Briis", postalCodes: ["91640"], department: "91", departmentName: "Essonne", population: 2345 },
  { slug: "forges-les-bains", name: "Forges-les-Bains", postalCodes: ["91470"], department: "91", departmentName: "Essonne", population: 4234 },
  { slug: "gif-sur-yvette", name: "Gif-sur-Yvette", postalCodes: ["91190"], department: "91", departmentName: "Essonne", population: 22234 },
  { slug: "gironville-sur-essonne", name: "Gironville-sur-Essonne", postalCodes: ["91720"], department: "91", departmentName: "Essonne", population: 567 },
  { slug: "gometz-la-ville", name: "Gometz-la-Ville", postalCodes: ["91400"], department: "91", departmentName: "Essonne", population: 2678 },
  { slug: "gometz-le-chatel", name: "Gometz-le-Châtel", postalCodes: ["91940"], department: "91", departmentName: "Essonne", population: 2567 },
  { slug: "grigny", name: "Grigny", postalCodes: ["91350"], department: "91", departmentName: "Essonne", population: 28234 },
  { slug: "guibeville", name: "Guibeville", postalCodes: ["91630"], department: "91", departmentName: "Essonne", population: 567 },
  { slug: "guillerval", name: "Guillerval", postalCodes: ["91690"], department: "91", departmentName: "Essonne", population: 345 },
  { slug: "igny", name: "Igny", postalCodes: ["91430"], department: "91", departmentName: "Essonne", population: 11234 },
  { slug: "itteville", name: "Itteville", postalCodes: ["91760"], department: "91", departmentName: "Essonne", population: 6789 },
  { slug: "janville-sur-juine", name: "Janville-sur-Juine", postalCodes: ["91510"], department: "91", departmentName: "Essonne", population: 1789 },
  { slug: "janvry", name: "Janvry", postalCodes: ["91640"], department: "91", departmentName: "Essonne", population: 678 },
  { slug: "juvisy-sur-orge", name: "Juvisy-sur-Orge", postalCodes: ["91260"], department: "91", departmentName: "Essonne", population: 17234 },
  { slug: "la-ferte-alais", name: "La Ferté-Alais", postalCodes: ["91590"], department: "91", departmentName: "Essonne", population: 4234 },
  { slug: "la-foret-le-roi", name: "La Forêt-le-Roi", postalCodes: ["91410"], department: "91", departmentName: "Essonne", population: 567 },
  { slug: "la-foret-sainte-croix", name: "La Forêt-Sainte-Croix", postalCodes: ["91150"], department: "91", departmentName: "Essonne", population: 234 },
  { slug: "la-norville", name: "La Norville", postalCodes: ["91290"], department: "91", departmentName: "Essonne", population: 4234 },
  { slug: "la-ville-du-bois", name: "La Ville-du-Bois", postalCodes: ["91620"], department: "91", departmentName: "Essonne", population: 7234 },
  { slug: "lardy", name: "Lardy", postalCodes: ["91510"], department: "91", departmentName: "Essonne", population: 6234 },
  { slug: "le-coudray-montceaux", name: "Le Coudray-Montceaux", postalCodes: ["91830"], department: "91", departmentName: "Essonne", population: 4234 },
  { slug: "le-plessis-pate", name: "Le Plessis-Pâté", postalCodes: ["91220"], department: "91", departmentName: "Essonne", population: 5234 },
  { slug: "le-val-saint-germain", name: "Le Val-Saint-Germain", postalCodes: ["91530"], department: "91", departmentName: "Essonne", population: 1678 },
  { slug: "leudeville", name: "Leudeville", postalCodes: ["91630"], department: "91", departmentName: "Essonne", population: 1234 },
  { slug: "leuville-sur-orge", name: "Leuville-sur-Orge", postalCodes: ["91310"], department: "91", departmentName: "Essonne", population: 4567 },
  { slug: "limours", name: "Limours", postalCodes: ["91470"], department: "91", departmentName: "Essonne", population: 6789 },
  { slug: "linas", name: "Linas", postalCodes: ["91310"], department: "91", departmentName: "Essonne", population: 7234 },
  { slug: "lisses", name: "Lisses", postalCodes: ["91090"], department: "91", departmentName: "Essonne", population: 8234 },
  { slug: "longpont-sur-orge", name: "Longpont-sur-Orge", postalCodes: ["91310"], department: "91", departmentName: "Essonne", population: 7234 },
  { slug: "maisse", name: "Maisse", postalCodes: ["91720"], department: "91", departmentName: "Essonne", population: 2789 },
  { slug: "marcoussis", name: "Marcoussis", postalCodes: ["91460"], department: "91", departmentName: "Essonne", population: 8234 },
  { slug: "marolles-en-beauce", name: "Marolles-en-Beauce", postalCodes: ["91150"], department: "91", departmentName: "Essonne", population: 345 },
  { slug: "marolles-en-hurepoix", name: "Marolles-en-Hurepoix", postalCodes: ["91630"], department: "91", departmentName: "Essonne", population: 5234 },
  { slug: "mennecy", name: "Mennecy", postalCodes: ["91540"], department: "91", departmentName: "Essonne", population: 15234 },
  { slug: "mereville", name: "Méréville", postalCodes: ["91660"], department: "91", departmentName: "Essonne", population: 3234 },
  { slug: "merobert", name: "Mérobert", postalCodes: ["91780"], department: "91", departmentName: "Essonne", population: 678 },
  { slug: "mespuits", name: "Mespuits", postalCodes: ["91150"], department: "91", departmentName: "Essonne", population: 234 },
  { slug: "milly-la-foret", name: "Milly-la-Forêt", postalCodes: ["91490"], department: "91", departmentName: "Essonne", population: 4789 },
  { slug: "moigny-sur-ecole", name: "Moigny-sur-École", postalCodes: ["91490"], department: "91", departmentName: "Essonne", population: 1234 },
  { slug: "mondeville", name: "Mondeville", postalCodes: ["91590"], department: "91", departmentName: "Essonne", population: 567 },
  { slug: "monnerville", name: "Monnerville", postalCodes: ["91930"], department: "91", departmentName: "Essonne", population: 456 },
  { slug: "montgeron", name: "Montgeron", postalCodes: ["91230"], department: "91", departmentName: "Essonne", population: 25234 },
  { slug: "montlhery", name: "Montlhéry", postalCodes: ["91310"], department: "91", departmentName: "Essonne", population: 7789 },
  { slug: "morangis", name: "Morangis", postalCodes: ["91420"], department: "91", departmentName: "Essonne", population: 13234 },
  { slug: "morigny-champigny", name: "Morigny-Champigny", postalCodes: ["91150"], department: "91", departmentName: "Essonne", population: 5234 },
  { slug: "morsang-sur-orge", name: "Morsang-sur-Orge", postalCodes: ["91390"], department: "91", departmentName: "Essonne", population: 22234 },
  { slug: "morsang-sur-seine", name: "Morsang-sur-Seine", postalCodes: ["91250"], department: "91", departmentName: "Essonne", population: 567 },
  { slug: "nainville-les-roches", name: "Nainville-les-Roches", postalCodes: ["91750"], department: "91", departmentName: "Essonne", population: 567 },
  { slug: "nozay", name: "Nozay", postalCodes: ["91620"], department: "91", departmentName: "Essonne", population: 5234 },
  { slug: "ollainville", name: "Ollainville", postalCodes: ["91290"], department: "91", departmentName: "Essonne", population: 6234 },
  { slug: "oncy-sur-ecole", name: "Oncy-sur-École", postalCodes: ["91490"], department: "91", departmentName: "Essonne", population: 567 },
  { slug: "ormoy", name: "Ormoy", postalCodes: ["91540"], department: "91", departmentName: "Essonne", population: 1234 },
  { slug: "orsay", name: "Orsay", postalCodes: ["91400"], department: "91", departmentName: "Essonne", population: 17234 },
  { slug: "orveau", name: "Orveau", postalCodes: ["91590"], department: "91", departmentName: "Essonne", population: 234 },
  { slug: "palaiseau", name: "Palaiseau", postalCodes: ["91120"], department: "91", departmentName: "Essonne", population: 36234 },
  { slug: "paray-vieille-poste", name: "Paray-Vieille-Poste", postalCodes: ["91550"], department: "91", departmentName: "Essonne", population: 8234 },
  { slug: "pecqueuse", name: "Pecqueuse", postalCodes: ["91470"], department: "91", departmentName: "Essonne", population: 678 },
  { slug: "plessis-saint-benoist", name: "Plessis-Saint-Benoist", postalCodes: ["91410"], department: "91", departmentName: "Essonne", population: 234 },
  { slug: "ponthevrard", name: "Ponthévrard", postalCodes: ["91410"], department: "91", departmentName: "Essonne", population: 345 },
  { slug: "prunay-sur-essonne", name: "Prunay-sur-Essonne", postalCodes: ["91720"], department: "91", departmentName: "Essonne", population: 567 },
  { slug: "puiselet-le-marais", name: "Puiselet-le-Marais", postalCodes: ["91150"], department: "91", departmentName: "Essonne", population: 234 },
  { slug: "pussay", name: "Pussay", postalCodes: ["91740"], department: "91", departmentName: "Essonne", population: 2345 },
  { slug: "quincy-sous-senart", name: "Quincy-sous-Sénart", postalCodes: ["91480"], department: "91", departmentName: "Essonne", population: 8234 },
  { slug: "richarville", name: "Richarville", postalCodes: ["91410"], department: "91", departmentName: "Essonne", population: 567 },
  { slug: "ris-orangis", name: "Ris-Orangis", postalCodes: ["91130"], department: "91", departmentName: "Essonne", population: 29234 },
  { slug: "roinville", name: "Roinville", postalCodes: ["91410"], department: "91", departmentName: "Essonne", population: 567 },
  { slug: "saclas", name: "Saclas", postalCodes: ["91690"], department: "91", departmentName: "Essonne", population: 2345 },
  { slug: "saclay", name: "Saclay", postalCodes: ["91400"], department: "91", departmentName: "Essonne", population: 3678 },
  { slug: "saint-aubin", name: "Saint-Aubin", postalCodes: ["91190"], department: "91", departmentName: "Essonne", population: 678 },
  { slug: "saint-cheron", name: "Saint-Chéron", postalCodes: ["91530"], department: "91", departmentName: "Essonne", population: 5234 },
  { slug: "saint-cyr-la-riviere", name: "Saint-Cyr-la-Rivière", postalCodes: ["91690"], department: "91", departmentName: "Essonne", population: 234 },
  { slug: "saint-cyr-sous-dourdan", name: "Saint-Cyr-sous-Dourdan", postalCodes: ["91410"], department: "91", departmentName: "Essonne", population: 1234 },
  { slug: "saint-escobille", name: "Saint-Escobille", postalCodes: ["91410"], department: "91", departmentName: "Essonne", population: 234 },
  { slug: "saint-germain-les-arpajon", name: "Saint-Germain-lès-Arpajon", postalCodes: ["91180"], department: "91", departmentName: "Essonne", population: 10234 },
  { slug: "saint-germain-les-corbeil", name: "Saint-Germain-lès-Corbeil", postalCodes: ["91250"], department: "91", departmentName: "Essonne", population: 8234 },
  { slug: "saint-hilaire", name: "Saint-Hilaire", postalCodes: ["91780"], department: "91", departmentName: "Essonne", population: 234 },
  { slug: "saint-jean-de-beauregard", name: "Saint-Jean-de-Beauregard", postalCodes: ["91940"], department: "91", departmentName: "Essonne", population: 456 },
  { slug: "saint-maurice-montcouronne", name: "Saint-Maurice-Montcouronne", postalCodes: ["91530"], department: "91", departmentName: "Essonne", population: 1234 },
  { slug: "saint-michel-sur-orge", name: "Saint-Michel-sur-Orge", postalCodes: ["91240"], department: "91", departmentName: "Essonne", population: 21234 },
  { slug: "saint-pierre-du-perray", name: "Saint-Pierre-du-Perray", postalCodes: ["91280"], department: "91", departmentName: "Essonne", population: 9234 },
  { slug: "saint-sulpice-de-favieres", name: "Saint-Sulpice-de-Favières", postalCodes: ["91910"], department: "91", departmentName: "Essonne", population: 456 },
  { slug: "saint-vrain", name: "Saint-Vrain", postalCodes: ["91770"], department: "91", departmentName: "Essonne", population: 3234 },
  { slug: "saint-yon", name: "Saint-Yon", postalCodes: ["91650"], department: "91", departmentName: "Essonne", population: 1789 },
  { slug: "sainte-genevieve-des-bois", name: "Sainte-Geneviève-des-Bois", postalCodes: ["91700"], department: "91", departmentName: "Essonne", population: 36234 },
  { slug: "saintry-sur-seine", name: "Saintry-sur-Seine", postalCodes: ["91250"], department: "91", departmentName: "Essonne", population: 6234 },
  { slug: "saulx-les-chartreux", name: "Saulx-les-Chartreux", postalCodes: ["91160"], department: "91", departmentName: "Essonne", population: 5234 },
  { slug: "savigny-sur-orge", name: "Savigny-sur-Orge", postalCodes: ["91600"], department: "91", departmentName: "Essonne", population: 37234 },
  { slug: "sermaise", name: "Sermaise", postalCodes: ["91530"], department: "91", departmentName: "Essonne", population: 1678 },
  { slug: "soisy-sur-ecole", name: "Soisy-sur-École", postalCodes: ["91840"], department: "91", departmentName: "Essonne", population: 2789 },
  { slug: "soisy-sur-seine", name: "Soisy-sur-Seine", postalCodes: ["91450"], department: "91", departmentName: "Essonne", population: 7789 },
  { slug: "souzy-la-briche", name: "Souzy-la-Briche", postalCodes: ["91580"], department: "91", departmentName: "Essonne", population: 456 },
  { slug: "torfou", name: "Torfou", postalCodes: ["91730"], department: "91", departmentName: "Essonne", population: 789 },
  { slug: "valpuiseaux", name: "Valpuiseaux", postalCodes: ["91720"], department: "91", departmentName: "Essonne", population: 234 },
  { slug: "varennes-jarcy", name: "Varennes-Jarcy", postalCodes: ["91480"], department: "91", departmentName: "Essonne", population: 2345 },
  { slug: "vaugrineuse", name: "Vaugrigneuse", postalCodes: ["91640"], department: "91", departmentName: "Essonne", population: 1567 },
  { slug: "vayres-sur-essonne", name: "Vayres-sur-Essonne", postalCodes: ["91820"], department: "91", departmentName: "Essonne", population: 789 },
  { slug: "verrieres-le-buisson", name: "Verrières-le-Buisson", postalCodes: ["91370"], department: "91", departmentName: "Essonne", population: 16234 },
  { slug: "vert-le-grand", name: "Vert-le-Grand", postalCodes: ["91810"], department: "91", departmentName: "Essonne", population: 2789 },
  { slug: "vert-le-petit", name: "Vert-le-Petit", postalCodes: ["91710"], department: "91", departmentName: "Essonne", population: 2567 },
  { slug: "videlles", name: "Videlles", postalCodes: ["91890"], department: "91", departmentName: "Essonne", population: 1234 },
  { slug: "vigneux-sur-seine", name: "Vigneux-sur-Seine", postalCodes: ["91270"], department: "91", departmentName: "Essonne", population: 32234 },
  { slug: "villabe", name: "Villabé", postalCodes: ["91100"], department: "91", departmentName: "Essonne", population: 5234 },
  { slug: "villebon-sur-yvette", name: "Villebon-sur-Yvette", postalCodes: ["91140"], department: "91", departmentName: "Essonne", population: 10234 },
  { slug: "villeconin", name: "Villeconin", postalCodes: ["91580"], department: "91", departmentName: "Essonne", population: 1567 },
  { slug: "villejust", name: "Villejust", postalCodes: ["91140"], department: "91", departmentName: "Essonne", population: 2789 },
  { slug: "villemoisson-sur-orge", name: "Villemoisson-sur-Orge", postalCodes: ["91360"], department: "91", departmentName: "Essonne", population: 7234 },
  { slug: "villeneuve-sur-auvers", name: "Villeneuve-sur-Auvers", postalCodes: ["91580"], department: "91", departmentName: "Essonne", population: 234 },
  { slug: "villiers-le-bacle", name: "Villiers-le-Bâcle", postalCodes: ["91190"], department: "91", departmentName: "Essonne", population: 1234 },
  { slug: "villiers-sur-orge", name: "Villiers-sur-Orge", postalCodes: ["91700"], department: "91", departmentName: "Essonne", population: 4234 },
  { slug: "viry-chatillon", name: "Viry-Châtillon", postalCodes: ["91170"], department: "91", departmentName: "Essonne", population: 32234 },
  { slug: "wissous", name: "Wissous", postalCodes: ["91320"], department: "91", departmentName: "Essonne", population: 7234 },
  { slug: "yerres", name: "Yerres", postalCodes: ["91330"], department: "91", departmentName: "Essonne", population: 30234 },
];

// Val-d'Oise (95) - Communes complémentaires
const valDOiseExtra: CityData[] = [
  { slug: "ableiges", name: "Ableiges", postalCodes: ["95450"], department: "95", departmentName: "Val-d'Oise", population: 1234 },
  { slug: "aincourt", name: "Aincourt", postalCodes: ["95510"], department: "95", departmentName: "Val-d'Oise", population: 987 },
  { slug: "ambleville", name: "Ambleville", postalCodes: ["95710"], department: "95", departmentName: "Val-d'Oise", population: 567 },
  { slug: "amenucourt", name: "Amenucourt", postalCodes: ["95510"], department: "95", departmentName: "Val-d'Oise", population: 345 },
  { slug: "andilly", name: "Andilly", postalCodes: ["95580"], department: "95", departmentName: "Val-d'Oise", population: 2567 },
  { slug: "argenteuil", name: "Argenteuil", postalCodes: ["95100"], department: "95", departmentName: "Val-d'Oise", population: 113234 },
  { slug: "arnouville", name: "Arnouville", postalCodes: ["95400"], department: "95", departmentName: "Val-d'Oise", population: 15234 },
  { slug: "arronville", name: "Arronville", postalCodes: ["95810"], department: "95", departmentName: "Val-d'Oise", population: 567 },
  { slug: "arthies", name: "Arthies", postalCodes: ["95420"], department: "95", departmentName: "Val-d'Oise", population: 345 },
  { slug: "asnieres-sur-oise", name: "Asnières-sur-Oise", postalCodes: ["95270"], department: "95", departmentName: "Val-d'Oise", population: 2789 },
  { slug: "attainville", name: "Attainville", postalCodes: ["95570"], department: "95", departmentName: "Val-d'Oise", population: 2234 },
  { slug: "auvers-sur-oise", name: "Auvers-sur-Oise", postalCodes: ["95430"], department: "95", departmentName: "Val-d'Oise", population: 7234 },
  { slug: "avernes", name: "Avernes", postalCodes: ["95450"], department: "95", departmentName: "Val-d'Oise", population: 789 },
  { slug: "baillet-en-france", name: "Baillet-en-France", postalCodes: ["95560"], department: "95", departmentName: "Val-d'Oise", population: 2345 },
  { slug: "banthelu", name: "Banthelu", postalCodes: ["95420"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "beauchamp", name: "Beauchamp", postalCodes: ["95250"], department: "95", departmentName: "Val-d'Oise", population: 9234 },
  { slug: "beaumont-sur-oise", name: "Beaumont-sur-Oise", postalCodes: ["95260"], department: "95", departmentName: "Val-d'Oise", population: 10234 },
  { slug: "bellefontaine", name: "Bellefontaine", postalCodes: ["95270"], department: "95", departmentName: "Val-d'Oise", population: 678 },
  { slug: "belloy-en-france", name: "Belloy-en-France", postalCodes: ["95270"], department: "95", departmentName: "Val-d'Oise", population: 2345 },
  { slug: "bernes-sur-oise", name: "Bernes-sur-Oise", postalCodes: ["95340"], department: "95", departmentName: "Val-d'Oise", population: 2789 },
  { slug: "berville", name: "Berville", postalCodes: ["95810"], department: "95", departmentName: "Val-d'Oise", population: 345 },
  { slug: "bessancourt", name: "Bessancourt", postalCodes: ["95550"], department: "95", departmentName: "Val-d'Oise", population: 8234 },
  { slug: "bezons", name: "Bezons", postalCodes: ["95870"], department: "95", departmentName: "Val-d'Oise", population: 31234 },
  { slug: "boisemont", name: "Boisemont", postalCodes: ["95000"], department: "95", departmentName: "Val-d'Oise", population: 567 },
  { slug: "boissy-l-aillerie", name: "Boissy-l'Aillerie", postalCodes: ["95650"], department: "95", departmentName: "Val-d'Oise", population: 2345 },
  { slug: "bonneuil-en-france", name: "Bonneuil-en-France", postalCodes: ["95500"], department: "95", departmentName: "Val-d'Oise", population: 789 },
  { slug: "bouqueval", name: "Bouqueval", postalCodes: ["95720"], department: "95", departmentName: "Val-d'Oise", population: 345 },
  { slug: "bouffemont", name: "Bouffémont", postalCodes: ["95570"], department: "95", departmentName: "Val-d'Oise", population: 6234 },
  { slug: "bray-et-lu", name: "Bray-et-Lû", postalCodes: ["95710"], department: "95", departmentName: "Val-d'Oise", population: 987 },
  { slug: "breancon", name: "Bréançon", postalCodes: ["95640"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "brignancourt", name: "Brignancourt", postalCodes: ["95640"], department: "95", departmentName: "Val-d'Oise", population: 345 },
  { slug: "bruyeres-sur-oise", name: "Bruyères-sur-Oise", postalCodes: ["95820"], department: "95", departmentName: "Val-d'Oise", population: 4234 },
  { slug: "buhy", name: "Buhy", postalCodes: ["95770"], department: "95", departmentName: "Val-d'Oise", population: 345 },
  { slug: "butry-sur-oise", name: "Butry-sur-Oise", postalCodes: ["95430"], department: "95", departmentName: "Val-d'Oise", population: 2234 },
  { slug: "cergy", name: "Cergy", postalCodes: ["95000", "95800"], department: "95", departmentName: "Val-d'Oise", population: 67234 },
  { slug: "champagne-sur-oise", name: "Champagne-sur-Oise", postalCodes: ["95660"], department: "95", departmentName: "Val-d'Oise", population: 4234 },
  { slug: "chars", name: "Chars", postalCodes: ["95750"], department: "95", departmentName: "Val-d'Oise", population: 2234 },
  { slug: "chatenay-en-france", name: "Châtenay-en-France", postalCodes: ["95190"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "chaumontel", name: "Chaumontel", postalCodes: ["95270"], department: "95", departmentName: "Val-d'Oise", population: 3456 },
  { slug: "chauvry", name: "Chauvry", postalCodes: ["95560"], department: "95", departmentName: "Val-d'Oise", population: 567 },
  { slug: "chennevieres-les-louvres", name: "Chennevières-lès-Louvres", postalCodes: ["95380"], department: "95", departmentName: "Val-d'Oise", population: 345 },
  { slug: "cherence", name: "Chérence", postalCodes: ["95510"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "clery-en-vexin", name: "Cléry-en-Vexin", postalCodes: ["95420"], department: "95", departmentName: "Val-d'Oise", population: 567 },
  { slug: "commeny", name: "Commeny", postalCodes: ["95450"], department: "95", departmentName: "Val-d'Oise", population: 345 },
  { slug: "courdimanche", name: "Courdimanche", postalCodes: ["95800"], department: "95", departmentName: "Val-d'Oise", population: 8234 },
  { slug: "cormeilles-en-parisis", name: "Cormeilles-en-Parisis", postalCodes: ["95240"], department: "95", departmentName: "Val-d'Oise", population: 25234 },
  { slug: "cormeilles-en-vexin", name: "Cormeilles-en-Vexin", postalCodes: ["95830"], department: "95", departmentName: "Val-d'Oise", population: 1234 },
  { slug: "courcelles-sur-viosne", name: "Courcelles-sur-Viosne", postalCodes: ["95650"], department: "95", departmentName: "Val-d'Oise", population: 456 },
  { slug: "deuil-la-barre", name: "Deuil-la-Barre", postalCodes: ["95170"], department: "95", departmentName: "Val-d'Oise", population: 23234 },
  { slug: "domont", name: "Domont", postalCodes: ["95330"], department: "95", departmentName: "Val-d'Oise", population: 16234 },
  { slug: "eaubonne", name: "Eaubonne", postalCodes: ["95600"], department: "95", departmentName: "Val-d'Oise", population: 26234 },
  { slug: "ecouen", name: "Écouen", postalCodes: ["95440"], department: "95", departmentName: "Val-d'Oise", population: 7234 },
  { slug: "enghien-les-bains", name: "Enghien-les-Bains", postalCodes: ["95880"], department: "95", departmentName: "Val-d'Oise", population: 12234 },
  { slug: "ennery", name: "Ennery", postalCodes: ["95300"], department: "95", departmentName: "Val-d'Oise", population: 2567 },
  { slug: "epiais-les-louvres", name: "Épiais-lès-Louvres", postalCodes: ["95380"], department: "95", departmentName: "Val-d'Oise", population: 567 },
  { slug: "epiais-rhus", name: "Épiais-Rhus", postalCodes: ["95810"], department: "95", departmentName: "Val-d'Oise", population: 678 },
  { slug: "epinay-champlatreux", name: "Épinay-Champlâtreux", postalCodes: ["95270"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "eragny", name: "Éragny", postalCodes: ["95610"], department: "95", departmentName: "Val-d'Oise", population: 17234 },
  { slug: "ermont", name: "Ermont", postalCodes: ["95120"], department: "95", departmentName: "Val-d'Oise", population: 29234 },
  { slug: "ezanville", name: "Ézanville", postalCodes: ["95460"], department: "95", departmentName: "Val-d'Oise", population: 9234 },
  { slug: "fontenay-en-parisis", name: "Fontenay-en-Parisis", postalCodes: ["95190"], department: "95", departmentName: "Val-d'Oise", population: 1234 },
  { slug: "fosses", name: "Fosses", postalCodes: ["95470"], department: "95", departmentName: "Val-d'Oise", population: 11234 },
  { slug: "franconville", name: "Franconville", postalCodes: ["95130"], department: "95", departmentName: "Val-d'Oise", population: 35234 },
  { slug: "fremainville", name: "Frémainville", postalCodes: ["95450"], department: "95", departmentName: "Val-d'Oise", population: 456 },
  { slug: "fremecourt", name: "Frémécourt", postalCodes: ["95830"], department: "95", departmentName: "Val-d'Oise", population: 345 },
  { slug: "frepillon", name: "Frépillon", postalCodes: ["95740"], department: "95", departmentName: "Val-d'Oise", population: 2567 },
  { slug: "frouville", name: "Frouville", postalCodes: ["95690"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "garges-les-gonesse", name: "Garges-lès-Gonesse", postalCodes: ["95140"], department: "95", departmentName: "Val-d'Oise", population: 44234 },
  { slug: "genainville", name: "Genainville", postalCodes: ["95420"], department: "95", departmentName: "Val-d'Oise", population: 567 },
  { slug: "gouzangrez", name: "Gouzangrez", postalCodes: ["95450"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "gonesse", name: "Gonesse", postalCodes: ["95500"], department: "95", departmentName: "Val-d'Oise", population: 27234 },
  { slug: "goussainville", name: "Goussainville", postalCodes: ["95190"], department: "95", departmentName: "Val-d'Oise", population: 32234 },
  { slug: "grisy-les-platres", name: "Grisy-les-Plâtres", postalCodes: ["95810"], department: "95", departmentName: "Val-d'Oise", population: 567 },
  { slug: "groslay", name: "Groslay", postalCodes: ["95410"], department: "95", departmentName: "Val-d'Oise", population: 8234 },
  { slug: "guiry-en-vexin", name: "Guiry-en-Vexin", postalCodes: ["95450"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "haravilliers", name: "Haravilliers", postalCodes: ["95640"], department: "95", departmentName: "Val-d'Oise", population: 456 },
  { slug: "haute-isle", name: "Haute-Isle", postalCodes: ["95780"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "hedouville", name: "Hédouville", postalCodes: ["95690"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "herblay", name: "Herblay", postalCodes: ["95220"], department: "95", departmentName: "Val-d'Oise", population: 29234 },
  { slug: "herouville-en-vexin", name: "Hérouville-en-Vexin", postalCodes: ["95300"], department: "95", departmentName: "Val-d'Oise", population: 678 },
  { slug: "hodent", name: "Hodent", postalCodes: ["95420"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "jagny-sous-bois", name: "Jagny-sous-Bois", postalCodes: ["95850"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "jouy-le-moutier", name: "Jouy-le-Moutier", postalCodes: ["95280"], department: "95", departmentName: "Val-d'Oise", population: 18234 },
  { slug: "la-chapelle-en-vexin", name: "La Chapelle-en-Vexin", postalCodes: ["95420"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "la-frette-sur-seine", name: "La Frette-sur-Seine", postalCodes: ["95530"], department: "95", departmentName: "Val-d'Oise", population: 4567 },
  { slug: "la-roche-guyon", name: "La Roche-Guyon", postalCodes: ["95780"], department: "95", departmentName: "Val-d'Oise", population: 456 },
  { slug: "labbeville", name: "Labbeville", postalCodes: ["95690"], department: "95", departmentName: "Val-d'Oise", population: 678 },
  { slug: "lassy", name: "Lassy", postalCodes: ["95270"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "le-bellay-en-vexin", name: "Le Bellay-en-Vexin", postalCodes: ["95750"], department: "95", departmentName: "Val-d'Oise", population: 345 },
  { slug: "le-heaulme", name: "Le Heaulme", postalCodes: ["95640"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "le-mesnil-aubry", name: "Le Mesnil-Aubry", postalCodes: ["95720"], department: "95", departmentName: "Val-d'Oise", population: 456 },
  { slug: "le-perchay", name: "Le Perchay", postalCodes: ["95450"], department: "95", departmentName: "Val-d'Oise", population: 678 },
  { slug: "le-plessis-bouchard", name: "Le Plessis-Bouchard", postalCodes: ["95130"], department: "95", departmentName: "Val-d'Oise", population: 8234 },
  { slug: "le-plessis-gassot", name: "Le Plessis-Gassot", postalCodes: ["95720"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "le-plessis-luzarches", name: "Le Plessis-Luzarches", postalCodes: ["95270"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "le-thillay", name: "Le Thillay", postalCodes: ["95500"], department: "95", departmentName: "Val-d'Oise", population: 4567 },
  { slug: "livilliers", name: "Livilliers", postalCodes: ["95300"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "longuesse", name: "Longuesse", postalCodes: ["95450"], department: "95", departmentName: "Val-d'Oise", population: 678 },
  { slug: "louvres", name: "Louvres", postalCodes: ["95380"], department: "95", departmentName: "Val-d'Oise", population: 11234 },
  { slug: "luzarches", name: "Luzarches", postalCodes: ["95270"], department: "95", departmentName: "Val-d'Oise", population: 4567 },
  { slug: "maffliers", name: "Maffliers", postalCodes: ["95560"], department: "95", departmentName: "Val-d'Oise", population: 1567 },
  { slug: "magny-en-vexin", name: "Magny-en-Vexin", postalCodes: ["95420"], department: "95", departmentName: "Val-d'Oise", population: 5678 },
  { slug: "marines", name: "Marines", postalCodes: ["95640"], department: "95", departmentName: "Val-d'Oise", population: 3456 },
  { slug: "margency", name: "Margency", postalCodes: ["95580"], department: "95", departmentName: "Val-d'Oise", population: 2789 },
  { slug: "mareil-en-france", name: "Mareil-en-France", postalCodes: ["95850"], department: "95", departmentName: "Val-d'Oise", population: 567 },
  { slug: "marly-la-ville", name: "Marly-la-Ville", postalCodes: ["95670"], department: "95", departmentName: "Val-d'Oise", population: 6234 },
  { slug: "menouville", name: "Menouville", postalCodes: ["95810"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "menucourt", name: "Menucourt", postalCodes: ["95180"], department: "95", departmentName: "Val-d'Oise", population: 5234 },
  { slug: "meriel", name: "Mériel", postalCodes: ["95630"], department: "95", departmentName: "Val-d'Oise", population: 5234 },
  { slug: "mery-sur-oise", name: "Méry-sur-Oise", postalCodes: ["95540"], department: "95", departmentName: "Val-d'Oise", population: 10234 },
  { slug: "moisselles", name: "Moisselles", postalCodes: ["95570"], department: "95", departmentName: "Val-d'Oise", population: 1567 },
  { slug: "montagny-en-vexin", name: "Montagny-en-Vexin", postalCodes: ["95420"], department: "95", departmentName: "Val-d'Oise", population: 345 },
  { slug: "montigny-les-cormeilles", name: "Montigny-lès-Cormeilles", postalCodes: ["95370"], department: "95", departmentName: "Val-d'Oise", population: 23234 },
  { slug: "montlignon", name: "Montlignon", postalCodes: ["95680"], department: "95", departmentName: "Val-d'Oise", population: 3234 },
  { slug: "montmagny", name: "Montmagny", postalCodes: ["95360"], department: "95", departmentName: "Val-d'Oise", population: 15234 },
  { slug: "montmorency", name: "Montmorency", postalCodes: ["95160"], department: "95", departmentName: "Val-d'Oise", population: 21234 },
  { slug: "mours", name: "Mours", postalCodes: ["95260"], department: "95", departmentName: "Val-d'Oise", population: 1567 },
  { slug: "moussy", name: "Moussy", postalCodes: ["95640"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "nerville-la-foret", name: "Nerville-la-Forêt", postalCodes: ["95590"], department: "95", departmentName: "Val-d'Oise", population: 567 },
  { slug: "nesles-la-vallee", name: "Nesles-la-Vallée", postalCodes: ["95690"], department: "95", departmentName: "Val-d'Oise", population: 2234 },
  { slug: "neuilly-en-vexin", name: "Neuilly-en-Vexin", postalCodes: ["95640"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "neuville-sur-oise", name: "Neuville-sur-Oise", postalCodes: ["95000"], department: "95", departmentName: "Val-d'Oise", population: 2234 },
  { slug: "nointel", name: "Nointel", postalCodes: ["95590"], department: "95", departmentName: "Val-d'Oise", population: 789 },
  { slug: "noisy-sur-oise", name: "Noisy-sur-Oise", postalCodes: ["95270"], department: "95", departmentName: "Val-d'Oise", population: 678 },
  { slug: "nucourt", name: "Nucourt", postalCodes: ["95420"], department: "95", departmentName: "Val-d'Oise", population: 789 },
  { slug: "omerville", name: "Omerville", postalCodes: ["95420"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "osny", name: "Osny", postalCodes: ["95520"], department: "95", departmentName: "Val-d'Oise", population: 18234 },
  { slug: "parmain", name: "Parmain", postalCodes: ["95620"], department: "95", departmentName: "Val-d'Oise", population: 5678 },
  { slug: "persan", name: "Persan", postalCodes: ["95340"], department: "95", departmentName: "Val-d'Oise", population: 13234 },
  { slug: "pierrelaye", name: "Pierrelaye", postalCodes: ["95480"], department: "95", departmentName: "Val-d'Oise", population: 9234 },
  { slug: "piscop", name: "Piscop", postalCodes: ["95350"], department: "95", departmentName: "Val-d'Oise", population: 567 },
  { slug: "pontoise", name: "Pontoise", postalCodes: ["95000"], department: "95", departmentName: "Val-d'Oise", population: 32234 },
  { slug: "presles", name: "Presles", postalCodes: ["95590"], department: "95", departmentName: "Val-d'Oise", population: 4234 },
  { slug: "puiseux-en-france", name: "Puiseux-en-France", postalCodes: ["95380"], department: "95", departmentName: "Val-d'Oise", population: 3789 },
  { slug: "puiseux-pontoise", name: "Puiseux-Pontoise", postalCodes: ["95650"], department: "95", departmentName: "Val-d'Oise", population: 1234 },
  { slug: "roissy-en-france", name: "Roissy-en-France", postalCodes: ["95700"], department: "95", departmentName: "Val-d'Oise", population: 2789 },
  { slug: "ronquerolles", name: "Ronquerolles", postalCodes: ["95690"], department: "95", departmentName: "Val-d'Oise", population: 345 },
  { slug: "sagy", name: "Sagy", postalCodes: ["95450"], department: "95", departmentName: "Val-d'Oise", population: 1234 },
  { slug: "saint-brice-sous-foret", name: "Saint-Brice-sous-Forêt", postalCodes: ["95350"], department: "95", departmentName: "Val-d'Oise", population: 15234 },
  { slug: "saint-clair-sur-epte", name: "Saint-Clair-sur-Epte", postalCodes: ["95770"], department: "95", departmentName: "Val-d'Oise", population: 987 },
  { slug: "saint-cyr-en-arthies", name: "Saint-Cyr-en-Arthies", postalCodes: ["95510"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "saint-gervais", name: "Saint-Gervais", postalCodes: ["95420"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "saint-gratien", name: "Saint-Gratien", postalCodes: ["95210"], department: "95", departmentName: "Val-d'Oise", population: 22234 },
  { slug: "saint-leu-la-foret", name: "Saint-Leu-la-Forêt", postalCodes: ["95320"], department: "95", departmentName: "Val-d'Oise", population: 16234 },
  { slug: "saint-martin-du-tertre", name: "Saint-Martin-du-Tertre", postalCodes: ["95270"], department: "95", departmentName: "Val-d'Oise", population: 2789 },
  { slug: "saint-ouen-l-aumone", name: "Saint-Ouen-l'Aumône", postalCodes: ["95310"], department: "95", departmentName: "Val-d'Oise", population: 24234 },
  { slug: "saint-prix", name: "Saint-Prix", postalCodes: ["95390"], department: "95", departmentName: "Val-d'Oise", population: 8234 },
  { slug: "saint-witz", name: "Saint-Witz", postalCodes: ["95470"], department: "95", departmentName: "Val-d'Oise", population: 3234 },
  { slug: "sannois", name: "Sannois", postalCodes: ["95110"], department: "95", departmentName: "Val-d'Oise", population: 28234 },
  { slug: "santeuil", name: "Santeuil", postalCodes: ["95640"], department: "95", departmentName: "Val-d'Oise", population: 567 },
  { slug: "sarcelles", name: "Sarcelles", postalCodes: ["95200"], department: "95", departmentName: "Val-d'Oise", population: 61234 },
  { slug: "seraincourt", name: "Seraincourt", postalCodes: ["95450"], department: "95", departmentName: "Val-d'Oise", population: 678 },
  { slug: "seugy", name: "Seugy", postalCodes: ["95270"], department: "95", departmentName: "Val-d'Oise", population: 567 },
  { slug: "soisy-sous-montmorency", name: "Soisy-sous-Montmorency", postalCodes: ["95230"], department: "95", departmentName: "Val-d'Oise", population: 18234 },
  { slug: "survilliers", name: "Survilliers", postalCodes: ["95470"], department: "95", departmentName: "Val-d'Oise", population: 4234 },
  { slug: "taverny", name: "Taverny", postalCodes: ["95150"], department: "95", departmentName: "Val-d'Oise", population: 27234 },
  { slug: "themericourt", name: "Théméricourt", postalCodes: ["95450"], department: "95", departmentName: "Val-d'Oise", population: 345 },
  { slug: "theuville", name: "Theuville", postalCodes: ["95810"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "us", name: "Us", postalCodes: ["95450"], department: "95", departmentName: "Val-d'Oise", population: 1567 },
  { slug: "valmondois", name: "Valmondois", postalCodes: ["95760"], department: "95", departmentName: "Val-d'Oise", population: 1234 },
  { slug: "vaudherland", name: "Vaudherland", postalCodes: ["95500"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "vaureal", name: "Vauréal", postalCodes: ["95490"], department: "95", departmentName: "Val-d'Oise", population: 17234 },
  { slug: "vemars", name: "Vémars", postalCodes: ["95470"], department: "95", departmentName: "Val-d'Oise", population: 2789 },
  { slug: "vetheuil", name: "Vétheuil", postalCodes: ["95510"], department: "95", departmentName: "Val-d'Oise", population: 789 },
  { slug: "viarmes", name: "Viarmes", postalCodes: ["95270"], department: "95", departmentName: "Val-d'Oise", population: 5234 },
  { slug: "vienne-en-arthies", name: "Vienne-en-Arthies", postalCodes: ["95510"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "vigny", name: "Vigny", postalCodes: ["95450"], department: "95", departmentName: "Val-d'Oise", population: 1234 },
  { slug: "villaines-sous-bois", name: "Villaines-sous-Bois", postalCodes: ["95570"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "villeron", name: "Villeron", postalCodes: ["95380"], department: "95", departmentName: "Val-d'Oise", population: 987 },
  { slug: "villiers-adam", name: "Villiers-Adam", postalCodes: ["95840"], department: "95", departmentName: "Val-d'Oise", population: 987 },
  { slug: "villiers-le-bel", name: "Villiers-le-Bel", postalCodes: ["95400"], department: "95", departmentName: "Val-d'Oise", population: 29234 },
  { slug: "villiers-le-sec", name: "Villiers-le-Sec", postalCodes: ["95720"], department: "95", departmentName: "Val-d'Oise", population: 234 },
  { slug: "wy-dit-joli-village", name: "Wy-dit-Joli-Village", postalCodes: ["95420"], department: "95", departmentName: "Val-d'Oise", population: 345 },
];

// Combine all extra cities
const allExtraCities: CityData[] = [
  ...seinEtMarneExtra,
  ...yvelinesExtra,
  ...essonneExtra,
  ...valDOiseExtra,
];

// Format for TypeScript output
function formatCityForTS(city: CityData): string {
  const population = city.population ? `, population: ${city.population}` : '';
  return `  { slug: "${city.slug}", name: "${city.name}", postalCodes: ${JSON.stringify(city.postalCodes)}, department: "${city.department}", departmentName: "${city.departmentName}"${population} },`;
}

// Main function
async function main(): Promise<void> {
  console.log('🏘️  Générateur de communes IDF');
  console.log('='.repeat(60));
  
  console.log(`\n📊 Communes supplémentaires générées:`);
  console.log(`   Seine-et-Marne (77): ${seinEtMarneExtra.length}`);
  console.log(`   Yvelines (78): ${yvelinesExtra.length}`);
  console.log(`   Essonne (91): ${essonneExtra.length}`);
  console.log(`   Val-d'Oise (95): ${valDOiseExtra.length}`);
  console.log(`   TOTAL: ${allExtraCities.length}`);

  // Output to file
  const output = allExtraCities.map(formatCityForTS).join('\n');
  
  console.log('\n✅ Données prêtes pour insertion dans cities-idf.ts');
  console.log('   Copier le contenu de scripts/cities-extra.ts dans le fichier approprié\n');
  
  // Write to a separate file for review
  const fs = await import('fs');
  fs.writeFileSync('scripts/cities-extra.ts', `// Communes IDF supplémentaires\n// Total: ${allExtraCities.length} communes\n\nexport const extraCities = [\n${output}\n];\n`);
  
  console.log('📁 Fichier créé: scripts/cities-extra.ts');
}

main();
